### PR TITLE
Unlock whole E46

### LINKED ISSUE #56: BMW Z4 Coupe - unlock rear hatch
As per the title, could it be possible to also unlock the rear hatch in the BMW z4 coupe along with the side doors when powering the car off?

### PR DESCRIPTION
**Pull request by nabucho**
Unlock the gas tank and trunk along with the doors on E46 and Z4
Fixes #56 

Maybe there are people that want trunk and gas tank locked, but this brings it on par with newer BMWs without the need for additional config setting.

### CODE REVIEW

**Comment by tedsalmon** [comment]
@nabucho 

Thanks! Let me mull this one over -- not all ZKEs are coded to unlock the High + Low side doors with one press of the central lock button -- neither of mine were seemingly from the factory, so that would actually create a regression as it currently unlocks all doors but not the hatch window, hatch or trunk.

Thanks again!
-Ted

**Comment by nabucho** [comment]
hmm, yeah, I can imagine different defaults for US and EU markets in many configurations. Happy to provide any readings, settings from my EU/GB E46 convertible to compare with yours so we can make a proper identification and unlock calls. Also, asking more BlueBus users about their cars / preferences can guide us, given there can be so many different confugurations to cover. This worked for me, using the codes you advised for people in #56 - so for my situation is perfect. But we should fine the most compatible solution.

**Comment by piersholt** [comment]
@nabucho I'd recommend accepting @tedsalmon's invitation to the BlueBus slack. There's multiple generations of ZKE, and they vary vastly in design. A command that works on one vehicle might fire the ejector seat on another 😄 . A quick sense check on slack could ensure the best use of your time.

**Comment by tedsalmon** [comment]
I'm closing this as @piersholt is refactoring the ZKE code.

**Pull request closed without merging**
