### PR TITLE
Adding french translation

### PR DESCRIPTION
**Pull request by machouse78**
Hello all. I decided to take time to add a french translation for my future bluetooth module (not received yet).
If someone could just test this code on his unit ?

### CODE REVIEW

**Comment by nabucho** [comment]
Good job, I will have a look and adjust the french accented characters.

**Comment by nabucho** [comment]
Hi Cedric,
please look at attached images. They highlight the space limits we are working within, and should provide you with a guidance how short the texts need to be. In general - in the EN translation we try to use most possible to be legible. In general, 16 chars is the max, but could be more or less depending on character width. 
I assume you are using the same terms as in native BMW dialogs or in Audio equipment, and cannot comment on what abbreviations would make sense and are understood by French speakers. 
Looking forward to see your next updates!
Happy new year!

IMG_6444

IMG_6443

IMG_6442

IMG_6441

IMG_6440

IMG_6439

IMG_6438

IMG_6445

IMG_6446

IMG_6449

IMG_6450

IMG_6437

IMG_6436

IMG_6451

IMG_6448

IMG_6447

IMG_6455

IMG_6453

IMG_6452

IMG_6454

**Comment by machouse78** [comment]
Hello [nabucho](https://github.com/nabucho) and thanks a lot for your quick feedback !
I've done a rework, depending of your screen pictures.
I've used abbreviations when it required (generally, french words are more longer than english words).
Wish you a happy new year too !

**Comment by nabucho** [comment]
Now all fits nicely, there were 2 mistakes in Oui / Non mismatched, fixed that.
Also deleted some spaces to fit.

**Review by nabucho — APPROVED** [review]
All good to include.

**Comment by machouse78** [comment]
Hello @nabucho and @tedsalmon, I juste received my Bluebus and I would try it with the french translation.
Could you provide me a hex file with the french translation ?
Best regards

**Comment by tedsalmon** [comment]
@machouse78 

[bluebus_1_3_4_p5.zip](https://github.com/tedsalmon/BlueBus/files/13907629/bluebus_1_3_4_p5.zip)

Fresh build off `master` for you.

-Ted

**Comment by machouse78** [comment]
Thanks a lot 🤩

**Pull request merged**
