### PR TITLE
Feature/voice assistant

### PR DESCRIPTION
**Pull request by tedsalmon**

### CODE REVIEW

**Review by nabucho — APPROVED** [review]
Seems fine to me :)

**Comment by tedsalmon** [comment]
@nabucho 

I have to extract the one commit and force push the branch. I've just been terribly busy :(

-Ted

**Comment by nabucho** [comment]
Added hack-y support for Voice Assistant initiated by phone. 
Not tested on BM83.
So the second commit is your call - I can live without it, but complements the Voice Assistant feature request #97

**Comment by nabucho** [comment]
It is rebased to current master branch.

**Pull request merged**
