### PR TITLE
Adding Polish translation

### PR DESCRIPTION
**Pull request by redssu**
Hey,

I noticed [Pull Request #75](https://github.com/tedsalmon/BlueBus/pull/75) and did the same job for Polish language

I tried to stay below 16 characters in length, but is that the right limit? I used UTF-16 char-codes which I belive are also used in the German translation

### CODE REVIEW

**Comment by nabucho** [comment]
The max size of text in general is 23 bytes, but that does not guarantee a fit to the screen, so shorter the better.

**Comment by redssu** [comment]
It turns out that Latin-1 does not support most Polish diacritic characters, so I converted them back to plain ASCII - I think they are still understandable anyway

I also changed a few lines to be longer than 16 characters, but only those that were really difficult to understand even for natives. If they are shortened by screen software, they will still be more understandable than their previous versions

**Comment by nabucho** [comment]
@redssu please have a look at the screens if they look correct and fit right.
Are you able compile and test yourself? Or install a .hex from me to check all the options yourself and eventually tweak?

IMG_0541
IMG_0540
IMG_0538
IMG_0536
IMG_0547
IMG_0546
IMG_0545
IMG_0544
IMG_0543
IMG_0542

**Comment by redssu** [comment]
I think it's clear and looks very nice, just as it should!

Unfortunately, I can't check it on my end because I don't have the BlueBus module yet - due to financial reasons, I plan to purchase it in the summer. Also, I currently have the Business CD radio, so I don't have the ability to verify everything. But I don't see any major or issues here, so it's OK.

I see that I misinterpreted the context of the "D. Rozdzielcza" text, so I corrected it to make the word more meaningful and replaced a couple of words in other lines.

**Review by nabucho — APPROVED** [review]
Work as expected, ready to merge if we have space in memory for it.

**Pull request merged**
