### PR TITLE
Localization support

### PR DESCRIPTION
**Pull request by AlexeyPribytkin**
Localization support added.

For now only Russian language is available.
As navigation software with modified glyphs is quite common in Russian-speaking countries, I made some quirks to support 192-255 range of ASCII symbols.

bluebus_localization

There are several string length limitations:
16 characters for menu items (including null terminator)
24 for other strings (including null terminator)

I believe that it's possible to overcome 16 limit for menu items and make menu selection wider like on a radio screen, but didn't find out how to that yet :)

Radio screen

Please, feel free to add new translations to the table.
[BlueBus translation table](https://docs.google.com/spreadsheets/d/1Js6hkJGdcbNjzkgZFEGgc0ZkwvGdAMGrrMlxjekeq_Y)

### CODE REVIEW

**Review by tedsalmon — APPROVED** [review]
Thanks a lot for this! I'll be making some changes before merging it to `master` and I'll link the diff here. The only big issue is in `local.c` as I namespace all functions with the name of the file they live in (to make it easy to find).

**Comment by dertimaushh** [comment]
> Localization support added.
> 
> 
> 
> For now only Russian language is available.
> 
> As navigation software with modified glyphs is quite common in Russian-speaking countries, I made some quirks to support 192-255 range of ASCII symbols.
> 
> 
> 
> bluebus_localization
> 
> 
> 
> There are several string length limitations:
> 
> 16 characters for menu items (including null terminator)
> 
> 24 for other strings (including null terminator)
> 
> 
> 
> I believe that it's possible to overcome 16 limit for menu items and make menu selection wider like on a radio screen, but didn't find out how to that yet :)
> 
> 
> 
> Radio screen
> 
> 
> 
> Please, feel free to add new translations to the table.
> 
> [BlueBus translation table](https://docs.google.com/spreadsheets/d/1Js6hkJGdcbNjzkgZFEGgc0ZkwvGdAMGrrMlxjekeq_Y)

Just added German. 

Best regards,
Tim

**Comment by tedsalmon** [comment]
> > Localization support added.
> > For now only Russian language is available.
> > As navigation software with modified glyphs is quite common in Russian-speaking countries, I made some quirks to support 192-255 range of ASCII symbols.
> > bluebus_localization
> > There are several string length limitations:
> > 16 characters for menu items (including null terminator)
> > 24 for other strings (including null terminator)
> > I believe that it's possible to overcome 16 limit for menu items and make menu selection wider like on a radio screen, but didn't find out how to that yet :)
> > Radio screen
> > Please, feel free to add new translations to the table.
> > [BlueBus translation table](https://docs.google.com/spreadsheets/d/1Js6hkJGdcbNjzkgZFEGgc0ZkwvGdAMGrrMlxjekeq_Y)
> 
> Just added German.
> 
> Best regards,
> Tim

Thank you!! I'll work on incorporating it this week :)

**Comment by dertimaushh** [comment]
Perfect.

Let me know in case you need any abbreviations for some of the entries. 

Best regards,
Tim

**Comment by tedsalmon** [comment]
@dertimaushh,

Is there a chance you could trim down a lot of these strings to stay under 16 characters? I know that's asking a lot of the German language where `UI` turns into `Benutzeroberfläche` :rofl: 

I have highlighted all the offending entries in bright red with a conditional rule, so when they are shortened, they'll automatically be un-highlighted :)

Thanks!
-Ted

**Comment by tedsalmon** [comment]
@AlexeyPribytkin,

Just FYI, I made some changes to your functionality as outlined here: https://github.com/tedsalmon/BlueBus/commit/61d26af562a4f77fe4efefeb82f9c934babf31ae

I hope that's okay! There were just some things I wanted to change for the sake of consistency.

P.S. Can I get your email so I can invite you to the BlueBus Slack?

Thanks!
-Ted

**Comment by dertimaushh** [comment]
> @dertimaushh,
> 
> Is there a chance you could trim down a lot of these strings to stay under 16 characters? I know that's asking a lot of the German language where `UI` turns into `Benutzeroberfläche` 🤣
> 
> I have highlighted all the offending entries in bright red with a conditional rule, so when they are shortened, they'll automatically be un-highlighted :)
> 
> Thanks!
> -Ted

Done :-) 

Best regards,
Tim

**Comment by dertimaushh** [comment]
@tedsalmon : Cleaned up the german translations after 1.17 beta testing.

**Pull request merged**
