### PR TITLE
Autounlock

### PR DESCRIPTION
**Pull request by tedsalmon**

### CODE REVIEW

**Comment by harryberlin** [comment]
CONFIG_OT_BLINKERS for gm unlock?

**Comment by tedsalmon** [comment]
@harryberlin,

Good catch! I'll fix this up. I'm going to alter the functionality a bit here anyways, but I wanted to get @uberchris2's changes out of his fork.

Thanks!
-Ted

**Comment by uberchris2** [comment]
@tedsalmon I would be happy to make branches in this repo if that would be easier? I would just need developer access to the repo. If not I’m happy to make future changes on a fork.

**Comment by tedsalmon** [comment]
@uberchris2,

Done!

Thanks,
-Ted

**Pull request merged**
